### PR TITLE
Hw3b

### PR DESCRIPTION
**Pull request by AntonMoberg**
Redid the pull request in the way you preferred. Everything else is the same as before

### CODE REVIEW

**Review by floridop — CHANGES_REQUESTED** [review]
Hi Anton!

Seems you have accidentally modified flopaganelli/HW3b/pokemoninfo.sh.skeleton. Please copy it over from the upstream repository for me to accept the pull request.

**Review by floridop — COMMENTED** [review]
Hi Anton
It has now become a total mess... what did you do?
Seems you replaced all files of everyone else. You only had to fetch my one file and copy it over...
This push I unfortunately cannot accept or it will mess up with everyone's files. Maybe you should revert to the previous commit and just manually download my original file and copy over... more info in the next comment.

**Comment by floridop** [comment]
I think you should do the following:

- `git checkout master`
- `git pull upstream master`
- `git checkout HW3b`
- `git revert 40ac6e0093171aa963789d37562a834d07690f4f` to go back to you previous commit and 
- `git merge master` to merge with the updated master
- `git push origin HW3b` to sync with github

Then the pull request should be clean. If you're in trouble let me know or visit me in my office, if nothing works I might just cherry-pick your pokemon exercise instead.
Regards,
Florido

**Comment by AntonMoberg** [comment]
Hi and sorry for the mess, gonna try fix it ASAP. One problem that i think is the cause of this is that when I write `git pull upstream master` I get error: insufficient permission for adding object to repository database .git/objects

Any clue what this is caused by?

**Pull request merged**
