### PR TITLE
Hw3b

### PR DESCRIPTION
**Pull request by gilettejr**
I ran in to some errors while going through your instructions, if this still isn't quite right I'll bring my laptop to the tutorial tomorrow to try and sort it

### CODE REVIEW

**Comment by floridop** [comment]
Hi Cameron,
No there is still a file of mine that has been modified. Either you checkout an older version of the file modified by me
`git checkout commithash -- filename`
where commithash is a former commit authored by me, or you just manually copy the file from my repository over yours and commit. I cannot accept the pull request as it is now

**Comment by floridop** [comment]
Check https://github.com/floridop/MNXB01-2017/pull/53/files to see the files changed

**Review by floridop — CHANGES_REQUESTED** [review]
I cannot accept this merge because the file flopaganelli/HW3b/pokemoninfo.sh is mine and you modified it. If you don't manage to solve I will only pick the changes that are done in your folder.

**Comment by floridop** [comment]
Actually while trying to integrate your changes I found yet another issue, that is, there are two versions of pokemoninfo.sh now and I don't know which one you want me to correct. I think to fix you should just delete the file  flopaganelli/HW3b/pokemoninfo.sh as I didn't have one, and do cleanup of what you do not want me to correct. The exercise must be in the HW3b folder. I checked

```
diff camrobertson/pokemoninfo.sh camrobertson/HW3b/pokemoninfo.sh 
32a33
> # Error if no argument is entered. Exercise 2 accounts for if the input is not a directory
41a43
> # Testing whether DBDIR is a directory
43a46
> # Exit if it is not a directory
56a60
> #Appropriate grep command for find file with this line
62a67
> #Easier to remove allplatforms.csv.ordered as well for debugging
78a84,85
> # For loop to cycle through every file in DBDIR
> 
80a88
> # Tail command to miss header line in each file, then write this to new file
90a99,101
> 
> #contents sorted alphanumerically
> 
111a123,124
> # Again, for loop to cycle through each file in DBDIR
> 
113a127,128
> # Function to remove directory part of filename
> 
115,116d129
< lines=$(tail -n +2 $files | wc -l) 
< echo "$fbname has $lines games"
117a131
> # Function to again remove headers, and count new lines (games) in each file
118a133
> lines=$(tail -n +2 $files | wc -l) 
119a135,137
> # Final output using above two functions
> 
> echo "$fbname has $lines games"
120a139,142
> # I am aware that there is an error here
> # as the top lines of the allplatforms files
> # will also be deleted. I was unsure of how to
> # correct for this

```

Seems there are differences and I don't know what is relevant. Please fix or I cannot proceed, eventually visit me in my office.

**Comment by gilettejr** [comment]
Hi Florido

Ok thanks, the code above is my final version for marking, but I can tidy
up the folders to make things easier

Cameron

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by floridop** [comment]
Hi Cameron
The text above is not really code, it is a diff between two files if you read the first line. Can you be more specific and point me exactly at what file you would like me to correct? If no other info I will assume is camrobertson/HW3b/pokemoninfo.sh and discard any other.

**Comment by floridop** [comment]
The commit 0c5e970f5310930af3ee17058a4b0749ba1eaf67 in my master already contains camrobertson/HW3b/pokemoninfo.sh , I assume that is what I should correct. 
You should `got checkout master`,`git pull upstream master` and compare it to your HW3b branch if you want:
`git diff master:camrobertson/HW3b/pokemoninfo.sh HW3b:camrobertson/HW3b/pokemoninfo.sh`
git diff master:camrobertson/HW3b/pokemoninfo.sh HW3b:camrobertson/pokemoninfo.sh

Eventually reopen this request if that is not what you want me to correct.

**Comment by gilettejr** [comment]
Hi Florido

Sorry, I've had a busy day so could only reply to you now. Yes, that is
correct

Thanks, I'm sorry I've managed to get so tangled up with Git!

Cameron

**Comment by floridop** [comment]
No prob everything is done now. Concentrate on the project!
Regards,
Florido

**Pull request closed without merging**
