### PR TITLE
Hw3b

### PR DESCRIPTION
**Pull request by gilettejr**

### CODE REVIEW

**Comment by floridop** [comment]
Hi Cameron, 
I am afraid I have to reject this pull request. Did you read my instructions? I'd like you to submit a pull request from a branch not from master.
Please follow Way A as described in https://github.com/floridop/MNXB01-2017/pull/30#issuecomment-337279978
Regards,
Florido

**Comment by gilettejr** [comment]
Hi Florido

Sorry about that, I got confused about which homework I had to do this for!
I'll follow your instructions and resubmit homework 3a now!

Cameron

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Thu, Oct 19, 2017 at 5:53 PM, Florido Paganelli <notifications@github.com

**Comment by gilettejr** [comment]
3b, not 3a!

**Comment by gilettejr** [comment]
Hi Florido

I've resubmitted the pull request from another branch now. I kept running
into error messages while going through your instructions though, if this
still isn't right can we discuss it during the tutorial tomorrow please?

Cameron

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_915382773452333175_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Thu, Oct 19, 2017 at 5:53 PM, Florido Paganelli <notifications@github.com

**Comment by floridop** [comment]
I guess we didn't manage to discuss?

**Pull request closed without merging**
