### PR TITLE
Hw3b branch pull request

### PR DESCRIPTION
**Pull request by alexanderhuusko**

### CODE REVIEW

**Review by floridop — CHANGES_REQUESTED** [review]
Hi Alexander
Please check https://github.com/floridop/MNXB01-2017/pull/41/files#diff-e8251b6253ceb547907b285e24bb7dc1
You're trying to add files to my personal folder, I cannot accept this pull request. You should remove files that write in my directory.

**Comment by floridop** [comment]
Thanks for this pull request! This is how it is properly done. Please check the fixes I requested!

**Comment by alexanderhuusko** [comment]
I believe I fixed it now. Commit b594ce2, the last one, no longer attempts to commit anything to your folder

**Comment by floridop** [comment]
Great Job! This will grant you some extra points :)

**Pull request merged**
