### PR TITLE
Hw3b

### PR DESCRIPTION
**Pull request by KarolisSul**
Adding my HW3b branch

### CODE REVIEW

**Comment by floridop** [comment]
Hi Karolis
Looks a bit messy, you changed one of my files and one from Mattias Åstrand. Can you revert/reset those to the version in my master?

**Comment by floridop** [comment]
Hi Karolis
I took your commit ae4494f6a2d7120300772f12e7498e2ff43e09ad and committed it to my master as 0c7fe3554d18bc39be2855e834c7db1241b7950a. You must have been sitting in front of a computer whose virtualmachine had been used by Mattias Åstrand because all your commits are authored by him. This was a leftover from the tutorial.

Please check that https://github.com/floridop/MNXB01-2017/blob/master/karsulinskas/HW3b/pokemoninfo.sh is actually what you want me to correct.

Closing the pull request.
Regards,
Florido

**Comment by KarolisSul** [comment]
Hello,
That is true, I used the same machine as Mattias has used, however I thought that since I used my github login information it would only update my part. That was my bad and I'll try to fix it as soon as posaible.
RegardsKarolis Sulinskas


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Florido Paganelli <notifications@github.com> Date: 02/11/2017  12:00  (GMT+01:00) To: floridop/MNXB01-2017 <MNXB01-2017@noreply.github.com> Cc: KarolisSul <nat15ksu@student.lu.se>, Author <author@noreply.github.com> Subject: Re: [floridop/MNXB01-2017] Hw3b (#64) 
Hi Karolis

I took your commit ae4494f and committed it to my master as 0c7fe35. You must have been sitting in front of a computer whose virtualmachine had been used by Mattias Åstrand because all your commits are authored by him. This was a leftover from the tutorial.
Please check that https://github.com/floridop/MNXB01-2017/blob/master/karsulinskas/HW3b/pokemoninfo.sh is actually what you want me to correct.
Closing the pull request.

Regards,

Florido

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/floridop/MNXB01-2017","title":"floridop/MNXB01-2017","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/floridop/MNXB01-2017"}},"updates":{"snippets":[{"icon":"PERSON","message":"@floridop in #64: Hi Karolis\r\nI took your commit ae4494f6a2d7120300772f12e7498e2ff43e09ad and committed it to my master as 0c7fe3554d18bc39be2855e834c7db1241b7950a. You must have been sitting in front of a computer whose virtualmachine had been used by Mattias Åstrand because all your commits are authored by him. This was a leftover from the tutorial.\r\n\r\nPlease check that https://github.com/floridop/MNXB01-2017/blob/master/karsulinskas/HW3b/pokemoninfo.sh is actually what you want me to correct.\r\n\r\nClosing the pull request.\r\nRegards,\r\nFlorido"}],"action":{"name":"View Pull Request","url":"https://github.com/floridop/MNXB01-2017/pull/64#issuecomment-341387090"}}}

**Comment by floridop** [comment]
There's nothing to fix. Just check the file I'll be correcting is the one I should correct, and concentrate on the project!
Regards,
Florido

**Comment by KarolisSul** [comment]
Hello,

Yes that is the file I wrote and uploaded.

Regards
Karolis Sulinskas

**Pull request closed without merging**
