### PR TITLE
Added folder HW2a with a tar file containing the latex tutorial answers.

### PR DESCRIPTION
**Pull request by bolibomp**

### CODE REVIEW

**Comment by floridop** [comment]
Hi Robin,
Nice username :) 
Thanks for your pull request. I added your commit 5cf16acbad78bd0da0312271983599b4452a6966 (HW2b) to my repository with commit 5cf16acbad78bd0da0312271983599b4452a6966.

However, creating a pull request for a master branch is not the best way to use
github. The reason for this is that all the changes made after the pull request are forwarded to me,
but how do I know which one is relevant?

So I am going to close this pull request and you should submit another one that clarifies which commit 
I should integrate in my master branch.

Also check that you HW3b is in the right directory! Should be inside the directory with your name.

There are two ways to help me out:

## Way A: branching
The best is to create a specific branch for your pull request and then
continue developing on the master.

1) Go inside your working directory and pull the latest version of your repository.
   `git pull origin master`
2) update with the latest version of my repository
   `git pull upstream master`
3) sync your remote branch with my latest updates
  ` git push origin master`
4) create a branch for HW3b:
   `git branch HW3b`
5) checkout the branch:
   `git checkout HW3b`
6) push the branch to your remote repository
   `git push origin HW3b`
7) login into github, select the HW3b branch in your MNXB01 fork and submit a pull request.


## Way B: indicating a commit hash you want me to integrate

If you don't manage to do the above or you get lost, please resubmit a pull request of your master branch but write in the comment the commit hash of the change you want me to add.
You can find the hash by writing 
  `git log` 


**Example:**
```
commit 054df543d39e1106aa99bdd02744e9ec9d05440c
Author: Florido Paganelli <florido.paganelli@hep.lu.se>
Date:   Tue Sep 26 16:05:36 2017 +0200

   clarification on how the script should behave
```
the commit hash is `054df543d39e1106aa99bdd02744e9ec9d05440c`

**Comment by bolibomp** [comment]
Ok so I tried to do it via git but cant get it to work at all. My git
directory doesn't work at all any more so I cant use the terminal. And now
I can't even find my code. Could you see any code the first time I tried to
send a pull request?

2017-10-13 16:54 GMT+02:00 Florido Paganelli <notifications@github.com>:

**Comment by floridop** [comment]
Hi Robin,
Your code is in your fork master , otherwise there will be no pull request:
https://github.com/bolibomp/MNXB01-2017
Looking at the above link, you confused master and branch in some way I don't understand, so for sure you did not follow my instructions, you must have done something else. For example you have a branch named "branch": 
https://github.com/bolibomp/MNXB01-2017/tree/branch
and another one called patch:
https://github.com/bolibomp/MNXB01-2017/tree/bolibomp-patch-1

Please follow the instructions above with the git client. Just clone your own fork to start with, it doesn't matter on which computer you are.

See my review comments on the pull request.

**Review by floridop — COMMENTED** [review]
the code you submitted is in the wrong path, you should move all your work on HW3b on the RobEmanuelsson folder. You created it in a HW3b/HW3b/ folder which appears to be a copy of mine. If you're lost it would be better for you to visit me in the office; in the state this is now I cannot correct your code.

**Pull request closed without merging**
