### PR TITLE
Hw3b

### PR DESCRIPTION
**Pull request by johanbook**

### CODE REVIEW

**Review by floridop — CHANGES_REQUESTED** [review]
Hi Johan
It seems you accidentally removed my flopaganelli/HW3b/pokemoninfo.sh.skeleton while editing your homework. Probably you moved the file or ran a 'git mv' . You should  not tamper the files in my flopaganelli/ folder therefore I cannot accept this pull.
Please restore my file (maybe a `git pull upstream master` will work?) for me to accept your changes.

**Comment by johanbook** [comment]
Hi!


I have not managed to restore the file (it won't follow when doing git pull upstream master).

Can I create a new fork and add my homework there?


Have a super day!


--
Med vänliga hälsningar,
Johan Book


________________________________
Från: Florido Paganelli <notifications@github.com>
Skickat: den 19 oktober 2017 12:36
Till: floridop/MNXB01-2017
Kopia: Johan Book; Author
Ämne: Re: [floridop/MNXB01-2017] Hw3b (#36)


@floridop requested changes on this pull request.

Hi Johan
It seems you accidentally removed my flopaganelli/HW3b/pokemoninfo.sh.skeleton while editing your homework. Probably you moved the file or ran a 'git mv' . You should not tamper the files in my flopaganelli/ folder therefore I cannot accept this pull.
Please restore my file (maybe a git pull upstream master will work?) for me to accept your changes.

**Comment by floridop** [comment]
Ok. I will cherry pick the changes that I consider relevant. Unfortunately this is one of the cases in which it takes quite some skill to resolve git issues.

**Comment by johanbook** [comment]
I have uploaded what I believe to be the correct version into a new branch with a new pull request.

Have a super day!

Med vänliga hälsningar,
Johan Book





-------- Originalmeddelande --------
Från: Florido Paganelli <notifications@github.com>
Datum: 2017-10-20 16:27 (GMT+01:00)
Till: floridop/MNXB01-2017 <MNXB01-2017@noreply.github.com>
Kopia: Johan Book <johanbook@hotmail.com>, Author <author@noreply.github.com>
Rubrik: Re: [floridop/MNXB01-2017] Hw3b (#36)


Ok. I will cherry pick the changes that I consider relevant. Unfortunately this is one of the cases in which it takes quite some skill to resolve git issues.

**Comment by floridop** [comment]
Uhm it's even worse now... I think your upstream might be misconfigured. I see all your colleagues commits and it seems you copied them over, I cannot accept this pull request. What did you exactly do?

**Comment by johanbook** [comment]
As I did not have access to the original computer I used git clone to copy it onto a computer. I then added the remote using git remote add upstream <url>.
Then git pull upstream master, create a new branch and git pull origin master.

Med vänliga hälsningar,
Johan Book




-------- Originalmeddelande --------
Från: Florido Paganelli <notifications@github.com>
Datum: 2017-10-20 16:43 (GMT+01:00)
Till: floridop/MNXB01-2017 <MNXB01-2017@noreply.github.com>
Kopia: Johan Book <johanbook@hotmail.com>, Author <author@noreply.github.com>
Rubrik: Re: [floridop/MNXB01-2017] Hw3b (#36)


Uhm it's even worse now... I think your upstream might be misconfigured. I see all your colleagues commits and it seems you copied them over, I cannot accept this pull request. What did you exactly do?

**Comment by floridop** [comment]
I see. But I think something is weird. If you pulled my merges it wouldn't look like that. Looks more like you copied the files over.
Can you show me the output of the following
`git remote -v`
thanks

**Comment by johanbook** [comment]
I don't have acess to any computer now but this is what it looks like from my phone.

Med vänliga hälsningar,
Johan Book





-------- Originalmeddelande --------
Från: Florido Paganelli <notifications@github.com>
Datum: 2017-10-20 16:49 (GMT+01:00)
Till: floridop/MNXB01-2017 <MNXB01-2017@noreply.github.com>
Kopia: Johan Book <johanbook@hotmail.com>, Author <author@noreply.github.com>
Rubrik: Re: [floridop/MNXB01-2017] Hw3b (#36)


I see. But I think something is weird. If you pulled my merges it wouldn't look like that. Looks more like you copied the files over.
Can you show me the output of the following
git remote -v
thanks

**Comment by floridop** [comment]
I can't see anything.

**Comment by floridop** [comment]
I just saw the new branch, is good enough! I will cherry pick your commits. You should not spend more time on this. Thanks!

**Pull request closed without merging**
