### PR TITLE
Homework 2b and 3b

### PR DESCRIPTION
**Pull request by mattastrand**
After following the instructions in the handout, I am committing the following changes:
I have created a folder called matastrand and another one called H2W within it.
In this last folder I have placed my solution to Homework 2a.

27/09/17 EDIT:
I have now added a HW3b subfolder in the matastrand folder containing the required bash script.

### CODE REVIEW

**Comment by floridop** [comment]
Hi Mattias,
Thanks for your pull request. I might delay the merge until I proceed to correct HW3b. But HW2b has been graded.
Regards,
Florido

**Comment by floridop** [comment]
Hi Mattias,
Thanks for your pull request. I added your commit 9adfbe5a51bfae402ea72bfb11e3a5464ba42bad (HW2b) to my repository.

However, creating a pull request for a master branch is not the best way to use
github. The reason for this is that all the changes made after the pull request are forwarded to me,
but how do I know which one is relevant?

So I am going to close this pull request and you should submit another one that clarifies which commit 
I should integrate in my master branch.

There are two ways to help me out:

## Way A: branching
The best is to create a specific branch for your pull request and then
continue developing on the master.

1) Go inside your working directory and pull the latest version of your repository.
   `git pull origin master`
2) update with the latest version of my repository
   `git pull upstream master`
3) sync your remote branch with my latest updates
  ` git push origin master`
4) create a branch for HW3b:
   `git branch HW3b`
5) checkout the branch:
   `git checkout HW3b`
6) push the branch to your remote repository
   `git push origin HW3b`
7) login into github, select the HW3b branch in your MNXB01 fork and submit a pull request.


## Way B: indicating a commit hash you want me to integrate

If you don't manage to do the above or you get lost, please resubmit a pull request of your master branch but write in the comment the commit hash of the change you want me to add.
You can find the hash by writing 
  `git log` 


**Example:**
```
commit 054df543d39e1106aa99bdd02744e9ec9d05440c
Author: Florido Paganelli <florido.paganelli@hep.lu.se>
Date:   Tue Sep 26 16:05:36 2017 +0200

   clarification on how the script should behave
```
the commit hash is `054df543d39e1106aa99bdd02744e9ec9d05440c`

**Comment by mattastrand** [comment]
Hello Florido,
Thank you for the feedback, I will start working on the improvement as soon
as possible.
I only have one question: the email you sent me seemed to hint that this
new pull request you want me to submit regards homework 3b and that my
solution to homework 2b has been accepted. Is that correct or should I send
new pull requests for both homework 2b and 3b?
Thank you in advance and see you soon!
Mattias


Il 10 ott 2017 20:38, "Florido Paganelli" <notifications@github.com> ha
scritto:

Hi Mattias,
Thanks for your pull request. I added your commit 9adfbe5
<https://github.com/floridop/MNXB01-2017/commit/9adfbe5a51bfae402ea72bfb11e3a5464ba42bad>
(HW2b) to my repository.

However, creating a pull request for a master branch is not the best way to
use
github. The reason for this is that all the changes made after the pull
request are forwarded to me,
but how do I know which one is relevant?

So I am going to close this pull request and you should submit another one
that clarifies which commit
I should integrate in my master branch.

There are two ways to help me out:
Way A: branching

The best is to create a specific branch for your pull request and then
continue developing on the master.

   1. Go inside your working directory and pull the latest version of your
   repository.
   git pull origin master
   2. update with the latest version of my repository
   git pull upstream master
   3. sync your remote branch with my latest updates
   git push origin master
   4. create a branch for HW3b:
   git branch HW3b
   5. checkout the branch:
   git checkout HW3b
   6. push the branch to your remote repository
   git push origin HW3b
   7. login into github, select the HW3b branch in your MNXB01 fork and
   submit a pull request.

Way B: indicating a commit hash you want me to integrate

If you don't manage to do the above or you get lost, please resubmit a pull
request of your master branch but write in the comment the commit hash of
the change you want me to add.
You can find the hash by writing
git log

*Example:*

commit 054df543d39e1106aa99bdd02744e9ec9d05440c
Author: Florido Paganelli <florido.paganelli@hep.lu.se>
Date:   Tue Sep 26 16:05:36 2017 +0200

   clarification on how the script should behave

the commit hash is 054df543d39e1106aa99bdd02744e9ec9d05440c

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/floridop/MNXB01-2017/pull/11#issuecomment-335568262>,
or mute the thread

**Comment by floridop** [comment]
Hi Mattias,
No, just for HW3b. I approved your HW2b, it's already in my upstream, you can check yourself:
https://github.com/floridop/MNXB01-2017/tree/master/matastrand/HW2a
Thanks!

**Comment by floridop** [comment]
Sorry I was a bit unclear about it. You can submit the pull request including HW2b and you will see that it is already merged. Go to the new pull request and you'll see the only changed files are relative to HW3b:
https://github.com/floridop/MNXB01-2017/pull/35/files
Cheers,
Florido

**Pull request closed without merging**
